name: Project auto-testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  Yolo_api_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r torch-requirements.txt
          pip install -r requirements.txt
          pip install pytest
          pip install httpx

      - name: Run health check test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_health

      - name: Run prediction by uid test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_prediction_by_uid

      - name: Run prediction by correct label test
        run: PYTHONPATH=. pytest -v Test/test_prediction_by_correct_label

      - name: Run prediction by wrong label test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_prediction_by_wrong_label

      - name: Run prediction by score test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_prediction_by_score