name: Project auto-testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r torch-requirements.txt
          pip install -r requirements.txt
          pip install pytest
          pip install httpx

      - name: Run health check test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_health

      - name: Run missing file test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_predict_missing_s3_key

      - name: Run invalid file type test
        run: PYTHONPATH=. pytest -v Test/test_api.py::test_predict_invalid_file_type