# The name of the workflow
name: yolo Deploy dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Docker image to deploy"
    secrets:
      EC2_SSH_KEY:
        required: true
      EC2_HOST_DEV:
        required: true
      EC2_USERNAME:
        required: true
      S3_BUCKET_DEV:
        required: true
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: "Docker image to deploy"

env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF
      - name: Copy deploy script to EC2
        run: |
          git checkout dev
          scp deploy_docker.sh ec2:/home/${{ secrets.EC2_USERNAME }}/
          ls -la
          scp docker-compose-files/docker-compose.div.yaml ec2:/home/${{ secrets.EC2_USERNAME }}/

      - name: Copy script to EC2
        run: |
          git checkout dev
          EC2_USERNAME=${{ secrets.EC2_USERNAME }}
          ssh ec2 "chmod +x /home/$EC2_USERNAME/deploy_docker.sh && bash /home/$EC2_USERNAME/deploy_docker.sh"

      - name: Execute script on EC2
        run: |
          echo """
          IMG_NAME="majdabbas99${{ inputs.image }}"
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_DEV }}
          """ > .env
          scp .env ec2:/home/${{ secrets.EC2_USERNAME }}/
          
          ssh ec2 "sudo docker compose -f docker-compose.div.yaml down \
              sudo docker compose -f docker-compose.div.yaml up -d"

